imports:
    - { resource: tables.yml }

services:
    blog.core:
        class: phpbb_ext_phpbbblog_blog
        arguments:
            - @controller.helper
            - @dbal.conn
            - @request
            - @template
            - @blog.model.categories

    blog.model.categories:
        class: phpbb_ext_phpbbblog_model_bag_categories
        arguments:
            - %tables.blog.categories%
            - @dbal.conn

    blog.model.posts:
        class: phpbb_ext_phpbbblog_model_bag_posts
        arguments:
            - %tables.blog.posts%
            - @dbal.conn
